name: Storybook publish (dev .io)

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Setup Node JS
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install dependencies
              run: npm ci
              working-directory: storybook/svelte-typescript-app
            - name: Build Storybook static
              run: npm run build-storybook
              working-directory: storybook/svelte-typescript-app
            - name: Upload
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                  server: yllo.io
                  username: ftpylloio
                  password: ${{ secrets.ALPHA_FTP_PASSWORD }}
                  local-dir: ./storybook/svelte-typescript-app/storybook-static/
                  server-dir: ./ui/
