name: Storybook publish (prod yllo.co/ui)

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Setup Node JS
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install dependencies
              run: npm ci
              working-directory: storybook/svelte-typescript-app
            - name: Build Storybook static
              run: npm run build-storybook
              working-directory: storybook/svelte-typescript-app
            - name: Upload
              uses: SamKirkland/FTP-Deploy-Action@4.1.0
              with:
                  server: 195.201.243.53
                  username: ftpylloco
                  password: ${{ secrets.PROD_FTP_PASSWORD }}
                  local-dir: ./storybook/svelte-typescript-app/storybook-static/
                  server-dir: ./ui/
